logging:
  level:
    root: info
  file:
    name: logs.txt
    path: /

server:
  tomcat:
    max-swallow-size: 10MB

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      open-in-view: false
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
app:
  image:
    bucket: C:\Users\yurka\IdeaProjects\resultat\images


